services:
  postgres:
    image: postgres:16
    container_name: southpark-postgres
    environment:
      POSTGRES_DB: southpark
      POSTGRES_USER: southpark
      POSTGRES_PASSWORD: southpark
    ports:
      - "5432:5432"
    volumes:
      - southpark_data:/var/lib/postgresql/data

volumes:
  southpark_data: